#!/usr/bin/env python3

import json
import sys


def prettyprint(fh):
    data = json.load(fh)
    print(json.dumps(data, indent=2, sort_keys=True))


if sys.argv[1:]:
    for path in sys.argv[1:]:
        with open(path, 'rt') as fh:
            prettyprint(fh)
else:
    prettyprint(sys.stdin)
