#!/usr/bin/env bash

function rename_mp3 {
    eyeD3 --no-color "$1" | pcregrep -q 'track:\s+\d+'
    if [ $? -eq 0 ]; then
        eyeD3 --to-v2.4 --rename='$track:num. $title' "$1"
    else
        eyeD3 --track=0 --to-v2.4 --rename='00. $title' "$1"
    fi
}

find "$1" -type f -iname '*.mp3' -print0 | while read -d $'\0' mp3
do
    rename_mp3 "$mp3"
done
