#!/usr/bin/bash

gpgdir="/tmp/ubuntu-gpg"
keyringdeb="http://mirror.pnl.gov/ubuntu//pool/main/u/ubuntu-keyring/ubuntu-keyring_2012.05.19_all.deb"

cd /tmp

# Download Ubuntu's keyring
wget -q "$keyringdeb" -O ubuntu-keyring.deb
bsdtar xf ubuntu-keyring.deb data.tar.gz
tar --strip-components=4 -xzf data.tar.gz ./usr/share/keyrings/ubuntu-archive-keyring.gpg

# Create a keyring and import Ubuntu's key
mkdir -p "$gpgdir"
gpg --no-default-keyring --keyring "$gpgdir/trustedkeys.gpg" --import ubuntu-archive-keyring.gpg

# Clean up
rm -f ubuntu-keyring.deb data.tar.gz ubuntu-archive-keyring.gpg

export GNUPGHOME="$gpgdir"

mountpoint="/run/media/michael/ubuntu-mirror"
if ! mountpoint -q "$mountpoint"; then
    echo "Mirror drive not mounted!"
    exit 1
fi

outpath="$mountpoint/ubuntu"
partnerpath="$mountpoint/canonical"

arch="i386,amd64"
section="main,restricted,universe,multiverse"

dist="precise,precise-security,precise-updates,precise-proposed,precise-backports"
dist="${dist},trusty,trusty-security,trusty-updates,trusty-proposed,trusty-backports"

partnerdist="precise,precise-security,precise-updates,precise-proposed,precise-backports"
partnerdist="${partnerdist},trusty,trusty-proposed"

method="http"
host="us.archive.ubuntu.com"
root="/ubuntu"

partnermethod="http"
partnerhost="archive.canonical.com"
partnerroot="/"

debmirror \
    --no-source \
    --arch="$arch" \
    --section="$section" \
    --dist="$dist" \
    --method="$method" \
    --host="$host" \
    --root="$root" \
    --progress \
    "$outpath" && \
\
debmirror \
    --arch="$arch" \
    --section="partner" \
    --dist="$partnerdist" \
    --method="$partnermethod" \
    --host="$partnerhost" \
    --root="$partnerroot" \
    --progress \
    "$partnerpath"

IFS=',' read -ra DIST <<< "$dist"
IFS=',' read -ra ARCH <<< "$arch"
for d in "${DIST[@]}"; do
    for a in "${ARCH[@]}"; do
        lfile="${outpath}/dists/${d}/Contents-${a}.gz"
        rfile="${method}://${host}${root}/dists/${d}/Contents-${a}.gz"
        echo -n "Fetching: $rfile ... "
        if ! wget -q -O "$lfile" "$rfile"; then
            echo "FAILED"
            exit 1
        fi
        echo "SUCCESS"
    done
done
